kuizu_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: KuizuUserBundle:Home:index }

kuizuuser_rank:
    pattern: /rank/{page}
    defaults: { _controller: KuizuUserBundle:Rank:index, page: 1 }
    requirements:
        page: \d+|me
