Kuizu\UserBundle\Entity\User:
    type: entity
    table: mk_user
    repositoryClass: Kuizu\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        score:
            type: integer
    oneToMany:
        answered:
            targetEntity: Kuizu\UserBundle\Entity\Answered
            mappedBy: user
        questions:
            targetEntity: Kuizu\GameBundle\Entity\Question
            mappedBy: author
    lifecycleCallbacks: {  }
