<?php

namespace Kuizu\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MangaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MangaRepository extends EntityRepository
{
    /**
     * @return array<\Kuizu\GameBundle\Entity\Manga>
     */
    public function findAllOrderByName()
    {
        return $this->createQueryBuilder('m')
            ->orderBy('m.name')
            ->getQuery()
            ->execute();
    }
}
