<?php

namespace Kuizu\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Kuizu\GameBundle\Entity\Manga;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function countByManga(Manga $manga)
    {
        $count = $this->createQueryBuilder('q')
            ->select('count(q.id) as total')
            ->where('q.manga = :mid')
            ->setParameter('mid', $manga->getId())
            ->getQuery()
            ->getScalarResult();

        return (int) $count[0]['total'];
    }
}
