<?php

namespace Kuizu\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Kuizu\GameBundle\Entity\Manga;
use Kuizu\UserBundle\Entity\User;

/**
 * AnsweredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnsweredRepository extends EntityRepository
{
    public function countByUserAndManga(User $user, Manga $manga)
    {
        $count = $this->createQueryBuilder('a')
            ->select('count(a.id) as total')
            ->where('a.user = :uid')
            ->andWhere('a.manga = :mid')
            ->setParameter('uid', $user->getId())
            ->setParameter('mid', $manga->getId())
            ->getQuery()
            ->getScalarResult();

        return (int) $count[0]['total'];
    }
}
