<?php

namespace Kuizu\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Kuizu\GameBundle\Entity\Manga;
use Kuizu\UserBundle\Entity\User;

/**
 * AnsweredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnsweredRepository extends EntityRepository
{
    public function countByUserAndManga(User $user, Manga $manga)
    {
        $count = $this->createQueryBuilder('a')
            ->select('count(a.id)')
            ->where('a.user = :uid')
            ->andWhere('a.manga = :mid')
            ->setParameter('uid', $user->getId())
            ->setParameter('mid', $manga->getId())
            ->getQuery()
            ->getSingleScalarResult();

        return (int) $count;
    }

    public function getQuestionIdsByUser(User $user)
    {
        return $this->createQueryBuilder('a')
            ->select('q.id')
            ->innerJoin('a.question', 'q')
            ->where('a.user = :uid')
            ->setParameter('uid', $user->getId())
            ->getQuery()
            ->getScalarResult();
    }
}
