parameters:
#    kuizu_front.example.class: Kuizu\FrontBundle\Example

services:
#    kuizu_front.example:
#        class: %kuizu_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
