kuizu_game_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: KuizuGameBundle:Default:index }

play:
    pattern: /play
    defaults: { _controller: KuizuGameBundle:Game:play }

ask:
    pattern: /ask
    defaults: { _controller: KuizuGameBundle:Game:ask }

list:
    pattern: /manga/list
    defaults: { _controller: KuizuGameBundle:Manga:list }
