parameters:
#    kuizu_game.example.class: Kuizu\GameBundle\Example

services:
#    kuizu_game.example:
#        class: %kuizu_game.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
