parameters:
    kuizugame.score.manager.class: Kuizu\GameBundle\Service\ScoreManager

services:
    kuizugame.score.manager:
        class: %kuizugame.score.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
